version: '3.4'

networks:
  apitwo-dev:
    driver: bridge 


services:
  apitwo:
    image: apitwo:latest
    depends_on:
      - "postgres_image"
      - "ftp-server"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9002:9002"
    environment:
      DB_CONNECTION_STRING: "host=postgres_image;port=5432;database=postgres;username=postgres;password=postgres"
    networks:
      - apitwo-dev  
  
  postgres_image:
    image: postgres:latest
    ports:
      - "5432"
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
      - ./dbscripts/sql.sql:/docker-entrypoint-initdb.d/sql.sql
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    networks:
      - apitwo-dev
  ftp-server:
    container_name: ftp-server
    image: stilliard/pure-ftpd:hardened
    ports:
       - "21:21"
       - "30000-30009:30000-30009"
    environment:
      PUBLICHOST: ${PUBLICHOST:-apitwo}
      FTP_USER_NAME: "localhost"
      FTP_USER_PASS: "localhost"
      FTP_USER_HOME: "/localhost/"
    restart: on-failure
    extra_hosts:
    - "host.docker.internal:host-gateway"
    networks:
      - apitwo-dev
volumes:
  db_volume:


     