version: '3.4'

networks:
  api-network:
    driver: bridge 


services:

 
    
 
      
    
      
      
      
  apifour:
    image: apifour:latest
    depends_on:
      - "postgres_image"
  
    build:
      context: .
      dockerfile: ./ApiFour/Dockerfile
    ports:
      - "9004:9004"
    environment:
      DB_CONNECTION_STRING: "host=postgres_image;port=5432;database=postgres;username=postgres;password=postgres"
    networks:
      - api-network  
  
  postgres_image:
    image: postgres:latest
    ports:
      - "5432"
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
      - ./dbscripts/sql.sql:/docker-entrypoint-initdb.d/sql.sql
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    networks:
      - api-network
   
volumes:
  db_volume:


     